### ISSUE TITLE
Asset revisioning

### ISSUE THREAD

**Issue by teneightfive** [uktrade/data-hub-frontend#206]
## The problem

Our asset revisioning is using a simple time based state from when the server starts. This causes cached assets to be re-downloaded even if nothing has changed. 

## Solution

To prevent this we should revision assets based on their contents. There are [gulp plugins](https://www.npmjs.com/package/gulp-rev-all) or we could investigate using webpack to append a hash to the filename.

We'll also need to create a manifest mapping filenames to their new filename which a middleware will need to check when in production.

**Comment by tyom** [comment]
Fixed in #251.
