### ISSUE TITLE
Trade Elements - Nunjucks macros/components

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-frontend#222]
## Problem
At the moment components used in Data Hub have been abstracted out to Trade Elements. We also need to re-structure how components are built so they are more standardised and easily shareable. This contains a lot of overhead at the moment when making changes to two projects.

## Solution/suggestion

Bring any macros in Data Hub from Trade Elements to give us visibility of what needs to be aligned
Convert Trade Element components to the Data Hub way of using components.

**Comment by ztolley** [comment]
Breaking this card down to a card per component

**Comment by ztolley** [comment]
Replaced with a card per component
