### ISSUE TITLE
Collections URL endpoints (e.g. `companies/`)

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-frontend#224]
Currently the system doesn't provide any views for collections (lists), e.g. /company should return a list of companies with, potentially, ability to search/filter the results.

Collections to address:
- contacts
- companies
- interactions
- investments
- investment interactions
etc.

If list of items is not available, consider adding a placeholder page or redirect.

**Comment by teneightfive** [comment]
@feedmypixel I removed the tech debt label as not sure if we'll tackle this in this batch. Adding these collections to each logical endpoint might require a bit of work. Especially to add the ability to filter results.

**Comment by teneightfive** [comment]
@feedmypixel it feels like this can be closed now?

Has been covered by a few PRs but these are some notable ones:

- #522
- #521
- #504
- #343
