### ISSUE TITLE
Create new Grid css 

### ISSUE THREAD

**Issue by ztolley** [uktrade/data-hub-frontend#243]
Remove the dependency on GDS elements grid by creating out own implementation, ideally on top of a well trusted grid solution.

18F and others chose http://neat.bourbon.io/ but version 2 of this gone gone away from the original and is really  not good. Either use the old one that you risk not being supported or find another.

@tyom had one in mind.

**Comment by ztolley** [comment]
http://lostgrid.org/docs.html

Consider dropping how we use grids all together and use a good 3rd party grid and specify the grids in the css

**Comment by jim68000** [comment]
Again, why are we dropping GDS from the app?
