### ISSUE TITLE
disableFormActions form prop doesn't quite do as it says

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-frontend#439]
## Problem
Currently we have a prob called [disableFormActions](https://github.com/uktrade/data-hub-frontend/blob/dcc35618e8c93e603a714e1ef346a8557074c098/src/templates/_macros/form.njk#L75) that actually hides the forms submit button

## Proposed Solution
- change the prop to `hideFormActions`
- add prop called `disableFormActions` that disables the forms submit

**Comment by tyom** [comment]
Why would one need to disable form submit button when calling that macro?
