### ISSUE TITLE
Review use of date libraries

### ISSUE THREAD

**Issue by teneightfive** [uktrade/data-hub-frontend#479]
## The problem

We're currently using multiple date libraries ([dateFns](https://date-fns.org/) and [moment](https://momentjs.com/)) to help with parsing and formatting of dates.

We had been favouring dateFns because it can be included more modular as moment requires including the whole thing.

## Solution

Review where we are using date libraries (both client and server) and understand their needs and see whether we can use one over the other removing the need for multiple date dependencies.

**Comment by teneightfive** [comment]
Issue related to modular moment on their repo: https://github.com/moment/moment/issues/2373

**Comment by ztolley** [comment]
Previously moment inflated client side code massively but we have upgrade webpack since then and the treeshaking May take care of it.
