### ISSUE TITLE
Separate client side and server side work

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-frontend#73]
## Problem

At the moment the clientside work and server side work are in together. This means you have to dig around to see what belongs where and it isn't clear what is what

### Clientside
- `/src/javascripts`
- `/src/sass` 
- `/src/public` 

### Serverside
- `/src/middleware`

## Solution/Suggestion

- Create an `src/application` folder for all server side work
- Create a `src/public` folder for all client side work
- Create a `src/common` folder for any shared utilities (validation/etc)

This folder structure can then be made ready for prod and placed into a `/dist` via an `npm build script`

> Names obviously all up for grabs

```
src
└── application
    └── middleware
    └── views
└── public
    └── javascripts
    └── sass
    └── images
     robots.txt
└── common
```

### Of Note 
Also reflect this structure in tests

**Comment by teneightfive** [comment]
This will use the proposed folder structure from #74 that will also accommodate separating client code from server code.
