### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-frontend#74]
## Problem
At the moment we are organising our code around roles

- `src/controllers`
- `src/repos`
- `src/services`

This involves an amount of digging around to find work and relies on naming conventions being followed to find associated files. That or `ctrl + click` throughs in the code.

## Solution/Suggestion
> Organize your Files Around Features, Not Roles

[Project Structure](https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/)
Then it will be a lot simplier to see what does what and what is connected.

- `src/contacts`
- `src/interactions`
- `src/ltd-company`
- `src/foreign`

Then if wanted we can follow a naming convention of `.controller`, `.service`, `.repo` and group any other files that may be needed with the structure
```
src
└── contacts
     contact.controller.js
     contact.service.js
     contact.repo.js
     contact.test.js
     README.md
```
> Groupings/Naming all up for grabs

**Comment by teneightfive** [comment]
Definitely agree that we should move to feature grouping as the app grows. Involves a lot of jumping around when building one feature at the moment. 

This is a suggestion for overall folder structure:

```
/config
  express.js
  index.js
  nunjucks.js
/[assets|client]
  /javascripts
  /stylesheets
/[server|app|src]
  /[feature|component|product]
    feature-name.controller.js
    feature-name.controller.test.js
    feature-name.service.js
    feature-name.service.test.js
    feature-name.repo.js
    feature-name.repo.test.js
    feature-name.view.njk
  /lib
  /public
  /views
    /_components
    /_includes
    /_layouts
```

Not convinced on where the generic layouts/components/includes should live though.

**Comment by feedmypixel** [comment]
this also covers discussion from #73

**Comment by tyom** [comment]
Can we rename 'views' to 'templates' please?

Layouts and macros are not views.

**Comment by teneightfive** [comment]
Yes, templates probably does make more sense.

**Comment by teneightfive** [comment]
For reference #151 starts to look at using express sub apps for routing and contained logic on investment.

**Comment by teneightfive** [comment]
After some discussion we came to a consensus of a proposed structure for now:

```
/config
  express.js
  index.js
  nunjucks.js
/assets
  /javascripts
  /stylesheets
/src
  /apps
    /[feature]
      feature-name.controller.js
      feature-name.service.js
      feature-name.repo.js
      index.js
      labels.js
      router.js

  /middleware
  /lib
  /templates
    /_components
    /_includes
    /_layouts
    /views
      feature-name.njk
  routes.js
  server.js
/public
/test
  /acceptance
  /unit
```

and a potential future structure:

```
/config
  express.js
  index.js
  nunjucks.js
/assets
  /javascripts
  /stylesheets
/src
  /apps
    /[feature]
      __tests__
        feature-name.controller.test.js
        feature-name.service.test.js
        feature-name.repo.test.js
      feature-name.controller.js
      feature-name.service.js
      feature-name.repo.js
      feature-name.njk
      index.js
      labels.js
      router.js
  /middleware
  /lib
  /templates
    /_components
    /_includes
    /_layouts
  routes.js
  server.js
/public
/test
  /acceptance
```

**Comment by teneightfive** [comment]
We've started to address a large majority of this and have most things now in feature apps.

I'm thinking we might need to continue this discussion to what the folder structure of a feature should look like. Here is an initial proposal.

Simple app:
```
/feature
  feature.controller.js
  index.js
  router.js
```

Complicated app:
```
/feature
  /controllers
    add.controller.js
    edit.controller.js
    view.controller.js
  /middleware
    get-details.middleware.js
  /services
    data.service.js
    form.service.js
  index.js
  labels.js
  repository.js
  router.js
```

### Questions

- Do we need type suffixes for controllers and services when in a subfolder?
- Do we need a `.repo` suffix or should we just call the file `repository.js`
- What happens when we almost have _sub-apps_ within a feature sub-app, for example interactions inside investment projects?

What are your thoughts @tyom @ztolley @feedmypixel?

**Comment by tyom** [comment]
New app structure is as follows:
```
apps/
  feature-app/
    controllers/
      add.js
      edit.js
      view.js
    services/
      data.js
      form.js
    index.js
    labels.js
    router.js
    services.js
    repos.js
  routes.js
```

`apps/` contains a collection of Express sub-apps each consisting of `index.js` which exposes `router` property. `router` is a standard Express router which an live in a local `router.js` file and imported from `index.js` or defined directly for simpler apps.

The public interface requires `router` property with Express router and has an optional `mountpath` which mounts sub app on designated path.

Sub app can also contain other files like controllers, services, repos and other files (notice plural as they export one or more properties). For more complex sub apps those files can be expanded into folders (e.g. `controllers/`) which have `index.js` exporting other modules in that folder, so the public api for importing sub apps modules doesn't change.

```js
const { router } = require('./apps/sub-app')
const subAppRouter = require('./apps/sub-app/router')
const { subAppController } = require('./apps/sub-app/controllers') // in sub-app/controllers.js
const subAppController, {controllerHandler} = require('./apps/sub-app/controllers') // in sub-app/controllers/index.js
```

**Comment by tyom** [comment]
Resolved in a number of PRs referenced above.
