### ISSUE TITLE
Centralised router config

### ISSUE THREAD

**Issue by teneightfive** [uktrade/data-hub-frontend#78]
## Problem

We currently refer to routes directly as strings when calling `res.redirect`. If routes change this will mean we'll have to make sure all occurrences of the original path will need to be changed or we'll end up with broken redirects.

## Suggestion

Either create a centralised router object or expose a `url` property on each controller which can be referenced when calling `res.redirect` or in tests.

## Further suggestion

It might also be cleaner to have all routes defined in the same place rather than within each controller so it's easier to see all available routes in one place. Controllers could then expose just their methods instead of the router.

**Comment by feedmypixel** [comment]
`Jira > DH-244` also contains info around this need

**Comment by rafenden** [comment]
`urls` module was introduced to address this issue.
